version: '3.7'

services:
  app-wasabil:
    build:
      args:
        WWWUSER: '${WWWUSER:-www-data}'
        WWWUSER_UID: '${WWWUSER_UID:-33}'
        APP_ENV: '${APP_ENV}'
    ports:
      - "8080:80"
    environment:
        WWWUSER: '${WWWUSER}'
        LARAVEL_SAIL: 1
        COMPOSER_ALLOW_SUPERUSER: 1  # Agregar esta línea
    volumes:
      - .:/var/www/html/app:delegated
    depends_on:
      - db-wasabil
    networks:
      - wasabil-red

  db-wasabil:
    image: "mysql:8.0"
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db-wasabil:/var/lib/mysql
    networks:
      - wasabil-red

networks:
  wasabil-red:
    driver: bridge

volumes:
  db-wasabil: